{% set name = "dataclasses-json" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f60be3405dee30b86ffbf6a436db8ba5efaeeb676bfda358e516a97aa7dfce4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - marshmallow >=3.3.0,<4.0.0
    - marshmallow-enum >=1.5.1,<2.0.0
    - typing_inspect >=0.4.0

test:
  imports:
    - dataclasses_json

about:
  home: https://github.com/lidatong/dataclasses-json
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easily serialize dataclasses to and from JSON
  doc_url: https://lidatong.github.io/dataclasses-json/
  dev_url: https://github.com/lidatong/dataclasses-json

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - mxr-conda
